Задание №8.3
sltnsprbkv/qa-automation-java pull request #10
Opened 2022-05-02 19:34 UTC by sltnsprbkv

2022-05-02 19:50 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/Application.java
> +        ((OrderedDistinctedMessageService)service).print(MessageOrder.DESC,
Показалось не логичным объявлять этот метод в интерфейсе MessageService

2022-05-02 19:52 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/OrderedDistinctedMessageService.java
> -                .forEach(printer::print);
Жалко удалять этот код( 
Кажется порядок вызова декораторов должен быть четко определен.

2022-05-05 15:53 UTC, kkmikhaylova requested changes

2022-05-05 15:53 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/Application.java
> +        ((OrderedDistinctedMessageService)service).print(MessageOrder.DESC,
Да нет, вполне логично. Если класс умеет печатать сообщения, то он реализует поведение "печатать". Интерфейсы как раз это поведение и определяют по сути, так что можно в интерфейс добавить этот метод
Если приходится приводить объект к определенному типу, как здесь, то скорее всего что-то спроектировано неверно. В общем случае должно хватать интерфейса, так как все его экземпляры должны поддерживать поведение, описанное в интерфейсе

2022-05-05 15:53 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/decorator/NumerateMessageDecorator.java
> +        return new Message(String.format("%d %s", ++messageCount, message.getBody()), message.getSeverity());
Тут может быть проблема в расширяемости. Если в `Message` добавится ещё один параметр, то мы столкнемся с тем, что мы вынуждены исправлять создание всех `Message` в коде. В этом конкретном случае можно добавить в класс `Message` конструктор
```
public Message(Message message, String body) {
    this(body, message.severity);
}
```
В таком случае добавление нового параметры потребует только изменений внутри самого класса `Message`

2022-05-05 15:53 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/OrderedDistinctedMessageService.java
> -                .forEach(printer::print);
Прочитай пока про паттерн https://www.baeldung.com/chain-of-responsibility-pattern, кажется мы к нему движемся 😄

2022-05-07 18:14 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/Application.java
> +        ((OrderedDistinctedMessageService)service).print(MessageOrder.DESC,
В данном случае метод печатает сообщения в обратном порядке, мне показалось, что этот метод относится только к OrderedDistinctedMessageService)

2022-05-07 18:19 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/OrderedDistinctedMessageService.java
> -                .forEach(printer::print);
Круто!! Попробую так сделать) надеюсь получится 🤞

2022-05-07 18:23 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/decorator/NumerateMessageDecorator.java
> +        return new Message(String.format("%d %s", ++messageCount, message.getBody()), message.getSeverity());
Хорошее замечание, спасибо!! Не пришло в голову, что так можно сделать)

2022-05-11 14:37 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/OrderedDistinctedMessageService.java
> -                .forEach(printer::print);
Круто, что получилось, молодец 🥇

2022-05-11 14:37 UTC, kkmikhaylova approved these changes

2022-05-15 11:32 UTC, merged