feat: completed task 12
sltnsprbkv/qa-automation-java pull request #15
Opened 2022-06-05 14:10 UTC by sltnsprbkv

2022-06-13 11:11 UTC, kkmikhaylova requested changes

2022-06-13 11:11 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/builder/MessageBuilder.java
> +    public MessageBuilder setUuid(UUID uuid) {
Обычно в билдерах методы именуются без префикса `set`
https://www.baeldung.com/creational-design-patterns#builder

2022-06-13 11:11 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/decorator/SeparateDecorator.java
> +    public final int PAGE_SIZE = 3;
А почему static удалил?

2022-06-13 11:11 UTC, kkmikhaylova commented on pom.xml
>    </dependencies>
У тебя тесты не запускаются на стадии mvn test, нужно в pom добавить
```
<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.22.0</version>
        </plugin>
    </plugins>
</build>
```

2022-06-13 11:11 UTC, kkmikhaylova commented on src/test/java/com/tcs/edu/decorator/NumerateMessageDecoratorTest.java
> +        assertEquals(decoratedMessage.getBody(), String.format("1 %s", messageBody));
В `assertEquals` первым аргументом указывается ожидаемое значение и вторым фактическое. Лучше соблюдать это, иначе можно запутаться

2022-06-13 11:11 UTC, kkmikhaylova commented on src/test/java/com/tcs/edu/repository/HashMapMessageRepositoryTest.java
> +        hashMapMessageRepository.save(new Message(RandomStringUtils.randomAlphabetic(10)));
Обычно в unit тестах проверяется работа только одного метода, иначе можно попасть в ситуацию, когда сломали методы save и delete, но тест продолжает работать, так как значение даже не записалось в мапу)
Править ничего не нужно, здесь иначе и не проверишь

2022-06-16 17:57 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/builder/MessageBuilder.java
> +    public MessageBuilder setUuid(UUID uuid) {
Буду знать, спасибо)

2022-06-16 17:58 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/decorator/SeparateDecorator.java
> +    public final int PAGE_SIZE = 3;
Не заметил, поправил

2022-06-16 17:59 UTC, sltnsprbkv commented on pom.xml
>    </dependencies>
добавил, понял только когда делал следующую задачу)

2022-06-16 18:01 UTC, sltnsprbkv commented on src/test/java/com/tcs/edu/decorator/NumerateMessageDecoratorTest.java
> +        assertEquals(decoratedMessage.getBody(), String.format("1 %s", messageBody));
Поправил

2022-06-16 18:04 UTC, sltnsprbkv commented on src/test/java/com/tcs/edu/repository/HashMapMessageRepositoryTest.java
> +        hashMapMessageRepository.save(new Message(RandomStringUtils.randomAlphabetic(10)));
Согласен, буду иметь ввиду)

2022-06-17 13:03 UTC, kkmikhaylova approved these changes

2022-06-17 13:36 UTC, merged