Dev
sltnsprbkv/qa-automation-java pull request #6
Opened 2022-04-17 20:13 UTC by sltnsprbkv

Задание №6

2022-04-17 20:14 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/decorator/SeverityMessageDecorator.java
> +                throw new AssertionError("Unknown severity value");
Вот тут не уверен. Что в таких случаях делают?

2022-04-19 15:31 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/decorator/SeverityMessageDecorator.java
> +                throw new AssertionError("Unknown severity value");
В этом конкретном случае я бы не выкидывала ошибку, так как проблема с логированием не должна приводить к проблемам с сервисов. Здесь лучше определить дефолтное поведение аналогично одному из кейсов выше, например, аналогично минорному.
```
case MINOR:
default:
    severitySign = "()";
    break;
```

2022-04-19 15:50 UTC, kkmikhaylova requested changes

2022-04-19 15:50 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/decorator/SeverityMessageDecorator.java
> +                severitySign = "(!!!)";
Отсюда можно сразу сделать `return String.format("%s %s", message, "(!!!)");` и немного сократить и упростить код. А сам формат `"%s %s"` вынести в статик переменную для переиспользования в каждом кейсе.

2022-04-19 15:50 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/decorator/TimestampMessageDecorator.java
>       * и увеличивает счетчик. При выводе разделяет "страницы" согласно PAGE_SIZE.
Доку актуализировать нужно

2022-04-19 15:50 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +    public static void init(Severity severity, String... message) {
А почему метод называется `init`, а не `print`? Название вводит в заблуждение

2022-04-19 15:50 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +            String finalMessage = NumerateMessageDecorator.messageCount % PAGE_SIZE == 0
Можно логику с разделением по `PAGE_SIZE` тоже вынести в отдельный `Decorator` и тут использовать

2022-04-19 15:50 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        for (String currentMessage: message) {
Можно с помощью Stream API причесать метод, чтоб выглядел читаемее
```
Arrays.stream(messages)
                .map(TimestampMessageDecorator::decorate)
                .map(NumerateMessageDecorator::decorate)
                ...
                .forEach(ConsolePrinter::print);
```

2022-04-19 15:50 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +    public static void init(Severity severity, String... message) {
Лучше назвать параметр `messages`, чтоб было понятно, что их там может быть несколько

2022-04-20 16:15 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/decorator/SeverityMessageDecorator.java
> +                severitySign = "(!!!)";
Да, действительно, код выглядит лучше)

2022-04-20 16:18 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/decorator/SeverityMessageDecorator.java
> +                throw new AssertionError("Unknown severity value");
Ок!

2022-04-20 16:18 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/decorator/TimestampMessageDecorator.java
>       * и увеличивает счетчик. При выводе разделяет "страницы" согласно PAGE_SIZE.
Ок

2022-04-20 16:19 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +    public static void init(Severity severity, String... message) {
Исправил

2022-04-20 16:19 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +    public static void init(Severity severity, String... message) {
Исправил

2022-04-20 16:22 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        for (String currentMessage: message) {
Сделал) 
`.map(message -> SeverityMessageDecorator.decorate(severity, message))`
Такое можно еще как то упростить?

2022-04-20 16:23 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +            String finalMessage = NumerateMessageDecorator.messageCount % PAGE_SIZE == 0
Сделал

2022-04-21 06:29 UTC, kkmikhaylova requested changes

2022-04-21 06:29 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +    public static int PAGE_SIZE = 3;
Неиспользуемая переменная осталась

2022-04-21 06:29 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        for (String currentMessage: message) {
Неа, дальше уже не упростить)

2022-04-21 07:09 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +    public static int PAGE_SIZE = 3;
А точно) Поправил

2022-04-21 07:16 UTC, kkmikhaylova approved these changes
Отличная работа)

2022-04-21 09:56 UTC, merged