Dev
sltnsprbkv/qa-automation-java pull request #7
Opened 2022-04-22 16:35 UTC by sltnsprbkv

Задание №7

2022-04-25 13:40 UTC, kkmikhaylova requested changes

2022-04-25 13:40 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        if (messageOrder.equals(MessageOrder.DESC)) Collections.reverse(finalMessages);
Когда задание читала, тоже подумала сразу, что легче сделать через `Collections.reverse()`. Решение хорошее, но нужно понимать, что оно требует дополнительных затрат ресурсов по сравнению с обратным циклом)
Ну и чтобы объекты туда сюда не перекладывать, можно реализовать метод
```
public static void print(Severity severity, Stream<String> messages) {
    messages
            .filter(Objects::nonNull)
            ...
            .forEach(ConsolePrinter::print);
}
```
И вызывать его отсюда и из метода выше
`print(Arrays.stream(messages));`
`print(finalMessages.stream());`
(ну и про реверс не забыть)

2022-04-25 13:40 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        var finalMessages = Arrays.asList(messages);
Тут бы тоже от перекладывания объектов туда сюда избавиться, но аналогии с методом выше. Жаль, не получится сразу в стрим перевести и везде использовать из-за необходимости вызывать `Collections.reverse()`, но можно хотя бы от массива избавиться

2022-04-25 16:10 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        if (messageOrder.equals(MessageOrder.DESC)) Collections.reverse(finalMessages);
Создал свой метод по reverse массива, и попытался упростить код

2022-04-25 20:20 UTC, kkmikhaylova requested changes

2022-04-25 20:20 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/utils/CustomCollectionOperations.java
> +    public static <T> void reverse(T[] array){
Велосипеды ^.^ Ладно, тут выглядит оправдано, давай оставим. Всё лучше, чем в `list` перегонять лишний раз. 
За дженерики 👍

2022-04-25 20:20 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        print(severity, messageOrder, doubling.equals(Doubling.DISTINCT)
Если `doubling` не равен `DISTINCT`, то получается, что мы зря инициализировали переменную `distinctMessages` выше, а это лишние затраты ресурсов

2022-04-25 20:20 UTC, kkmikhaylova commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        if (messageOrder.equals(MessageOrder.DESC)) CustomCollectionOperations.reverse(finalMessages);
Обычно стараются всё же сохранять фигурные скобки во всех ситуациях, ради читаемости. 
Не ошибка, править не обязательно)

2022-04-26 06:51 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        print(severity, messageOrder, doubling.equals(Doubling.DISTINCT)
Согласен! Не подумал про это)

2022-04-26 06:52 UTC, sltnsprbkv commented on src/main/java/com/tcs/edu/service/MessageService.java
> +        if (messageOrder.equals(MessageOrder.DESC)) CustomCollectionOperations.reverse(finalMessages);
Учту

2022-04-26 10:00 UTC, kkmikhaylova approved these changes

2022-04-29 12:24 UTC, merged